name: gestion_taches_app  
description: Application de gestion de tâches avec Firebase
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase - Versions stables
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  
  # Provider - Gestion d'état
  provider: ^6.1.1

  # Stockage local
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  
  # Hive - Cache local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # Réseau
  http: ^1.1.0
  connectivity_plus: ^5.0.2

  # Utilitaires
  intl: ^0.18.1
  equatable: ^2.0.5
  
  # les icônes et animations
  flutter_staggered_animations: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1


# dependency_overrides:
#   firebase_core_web: ^2.11.5
#   firebase_auth_web: ^5.9.9
#   cloud_firestore_web: ^3.10.9
#   _flutterfire_internals: ^1.3.25

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/sample_tasks.json
    - assets/images/           
    
  # Polices personnalisées 
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700